services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: data_science_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Madrid
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    restart: always
    depends_on:
      - postgres
    environment:
      DBeaver_USER: ${POSTGRES_USER}
      DBeaver_PASSWORD: ${POSTGRES_PASSWORD}
      DBeaver_DATABASE: ${POSTGRES_DB}
      DBeaver_HOST: postgres
      DBeaver_PORT: 5432
    ports:
      - 5901:5900

volumes:
  postgres_data:
