services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    # image: "postgres:15"
    container_name: "postgres"
    restart: always
    ports:
      - 5432:5432
    volumes:
      # - ./00_data_engineer:/00_data_engineer
      # - ./01_data_warehouse:/01_data_warehouse
      # - ./02_data_analyst:/02_data_analyst
      # - ./bak:/bak
      - pg_data:/var/lib/postgresql/data
    environment:
      # - POSTGRES_USER=dgerwig
      # - POSTGRES_PASSWORD=userpw
      # - POSTGRES_DB=piscineds
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Madrid
  pgadmin:
    build:
      context: ./docker/pgadmin
      dockerfile: Dockerfile
    # image: "dpage/pgadmin4"
    container_name: "pgadmin"
    restart: always
    ports:
      - 5050:80
    environment:
      # - PGADMIN_DEFAULT_EMAIL=admin@data.com
      # - PGADMIN_DEFAULT_PASSWORD=adminpw
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      # - PGADMIN_CONFIG_SERVER_MODE="False"
  # python:
  #   container_name: "python"
  #   working_dir: /02_data_analyst
  #   build: .
  #   volumes:
  #     - ./02_data_analyst:/02_data_analyst
  #     - ./03_data_scientist_01:/03_data_scientist_01
  #     - ./04_data_scientist_02:/04_data_scientist_02
volumes:
  pg_data:

  
# services:
  
#   postgres:
#     build:
#       context: ./docker/postgres
#       dockerfile: Dockerfile
#     # container_name: data_science_postgres
#     # image: "postgres:16"
#     container_name: "postgres"
#     restart: always
#     environment:
#       - POSTGRES_USER: ${POSTGRES_USER}
#       - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       - POSTGRES_DB: ${POSTGRES_DB}
#       - TZ: Europe/Madrid
#     ports:
#       - 5432:5432
#     volumes:
#       - pgadmin_data:/var/lib/postgresql/data
#       - ./scripts:/scripts
#     # networks:
#     #   - backend

#   pgadmin:
#     build:
#       context: ./docker/postgres
#       dockerfile: Dockerfile
#     # container_name: pgadmin
#     # image: "dpage/pgadmin4"
#     container_name: "pgadmin"
#     restart: always
#     environment:
#       - PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#       - PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#       # PGADMIN_CONFIG_SERVER_MODE: "False"
#     ports:
#       - 5050:80
#     depends_on:
#       - postgres
#     volumes:
#       # - pgadmin_data:/var/lib/postgresql/data
#       - ./scripts:/scripts
#     # networks:
#     #   - backend

# volumes:
#   postgres_data:
#   pgadmin_data:
    
# # networks:
# #   backend:
