services:
  
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    # container_name: data_science_postgres
    # image: "postgres:16"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Madrid
    ports:
      - 5432:5432
    volumes:
      # - ../00_data_engineer:/00_data_engineer
      - pgadmin_data:/var/lib/postgresql/data
      - ./scripts:/scripts
    # networks:
    #   - my_network

  pgadmin:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    # container_name: pgadmin
    # image: "dpage/pgadmin4"
    container_name: "pgadmin"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5050:80
    # depends_on:
    #   - postgres
    volumes:
      - ./pgadmin/var/lib/pgadmin:/var/lib/pgadmin
      - ./scripts:/scripts
    # networks:
    #   - my_network

volumes:
  postgres_data:
  pgadmin_data:

# networks:
#   my_network:
#     driver: bridge
