version: '3.1'

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: data_science_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Madrid
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - ./pgadmin/var/lib/pgadmin:/var/lib/pgadmin
      - ./scripts:/scripts
    # command: ["sh", "-c", "cat /scripts/create_connection.sql | psql -h postgres -U postgres"]

  # dbeaver:
  #   image: dbeaver/dbeaver-ce:latest
  #   container_name: dbeaver
  #   restart: always
  #   depends_on:
  #     - postgres
  #   environment:
  #     DBeaver_USER: ${POSTGRES_USER}
  #     DBeaver_PASSWORD: ${POSTGRES_PASSWORD}
  #     DBeaver_DATABASE: ${POSTGRES_DB}
  #     DBeaver_HOST: postgres
  #     DBeaver_PORT: 5432
  #   ports:
  #     - 5900:5900


volumes:
  postgres_data:
  pgadmin_data:
